name       : python-argh
version    : 0.28.1
release    : 7
source     :
    - https://github.com/neithere/argh/archive/v0.28.1.tar.gz : d13904a5c158cf8ac2a9cdf0764e5d4ec584ae73d6d362e89efcf63bcfe57690
homepage   : https://github.com/neithere/argh
license    : LGPL-3.0-or-later
component  : programming.python
summary    : An unobtrusive argparse wrapper with natural syntax
description: |
    Argh is a smart wrapper for argparse. Argparse is a very powerful tool; Argh just makes it easy to use.
builddeps  :
    - python-build
    - python-flit-core
    - python-installer
    - python-packaging
build      : |
    %python3_setup
install    : |
    %python3_install
