name       : python-argh
version    : 0.26.2
release    : 1
source     :
    - https://github.com/neithere/argh/archive/v0.26.2.tar.gz : eb5476ac788e5c4f5e01825455630218aba055c29240637988f4c99532e7bdb6
license    : GPL-3.0
component  : programming.python
summary    : An unobtrusive argparse wrapper with natural syntax
description: |
    An unobtrusive argparse wrapper with natural syntax
builddeps  : 
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
